Moment-Film/Moment_Film_Backend

.gitignore
build.gradle
src/main/java/com/team_7/moment_film/domain/customfilter/controller/FilterController.java
src/main/java/com/team_7/moment_film/domain/customfilter/entity/Filter.java
src/main/java/com/team_7/moment_film/domain/customfilter/service/FilterService.java
src/main/java/com/team_7/moment_film/domain/customframe/controller/FrameController.java
src/main/java/com/team_7/moment_film/domain/customframe/entity/Frame.java
src/main/java/com/team_7/moment_film/domain/customframe/service/FrameService.java
src/main/java/com/team_7/moment_film/domain/user/controller/UserController.java
src/main/java/com/team_7/moment_film/domain/user/dto/SearchResponseDto.java
src/main/java/com/team_7/moment_film/domain/user/repository/UserRepository.java
src/main/java/com/team_7/moment_film/domain/user/repository/UserRepositoryCustom.java
src/main/java/com/team_7/moment_film/domain/user/repository/UserRepositoryImpl.java
src/main/java/com/team_7/moment_film/domain/user/service/UserService.java
src/main/java/com/team_7/moment_film/global/config/SecurityConfig.java

body: 사용자 검색 기능 user 패키지에 추가
build.gradle에 Qclass 경로 설정추가
merge 후 user,post 경로 맞게 변경

feat: 사용자 검색 기능 추가

---

src/main/java/com/team_7/moment_film/domain/user/controller/UserController.java
src/main/java/com/team_7/moment_film/domain/user/dto/KakaoUserInfoDto.java
src/main/java/com/team_7/moment_film/domain/user/entity/User.java
src/main/java/com/team_7/moment_film/domain/user/service/KakaoService.java
src/main/java/com/team_7/moment_film/domain/user/service/UserService.java
src/main/java/com/team_7/moment_film/global/config/RestTemplateConfig.java
src/main/java/com/team_7/moment_film/global/config/SecurityConfig.java

- 카카오 계정으로 이미 회원가입을 했을 경우 바로 로그인(JWT) 발급
- User Entity에 카카오 유저와 일반 유저를 구분할 수 있는 isKakao(boolean) 필드 추가

Feat : 카카오 계정 로그인/회원가입 기능 추가

---

src/main/java/com/team_7/moment_film/domain/like/repository/LikeRepository.java
src/main/java/com/team_7/moment_film/domain/post/entity/Post.java
src/main/java/com/team_7/moment_film/domain/post/repository/PostRepository.java
src/main/java/com/team_7/moment_film/domain/user/controller/UserController.java
src/main/java/com/team_7/moment_film/domain/user/dto/ProfileResponseDto.java
src/main/java/com/team_7/moment_film/domain/user/entity/User.java
src/main/java/com/team_7/moment_film/domain/user/service/UserService.java
src/main/java/com/team_7/moment_film/global/config/SecurityConfig.java

- url path로 전달된 userId를 통해 해당 유저의 프로필 정보 조회
- userId, username, followerList, followingList, postList, postListCnt, likePosts 반환

feat : 프로필 조회 API 추가

---

src/main/java/com/team_7/moment_film/domain/user/service/UserService.java

body: 개인 정보 수정시 카카오유저 false로 바껴서 iskakao도 추가

fix: 개인정보 수정부분 iskakao 추가

---

src/main/java/com/team_7/moment_film/domain/user/repository/UserRepositoryImpl.java
src/main/java/com/team_7/moment_film/domain/user/service/UserService.java
src/main/java/com/team_7/moment_film/global/config/SecurityConfig.java

body: 사용자 검색 기능 로그인 필요없게 변경,
검색 결과가 없거나 키워드 없을 시 예외처리 추가,
개인정보 수정할 때 다른 필드 입력시 예외처리 추가

fix: 개인정보 수정 부분, 사용자 검색부분 수정

---

src/main/java/com/team_7/moment_film/domain/user/controller/UserController.java
src/main/java/com/team_7/moment_film/global/config/CorsConfig.java
src/main/java/com/team_7/moment_film/global/config/SecurityConfig.java
src/main/java/com/team_7/moment_film/global/filter/JwtLogoutFilter.java

body : 클라이언트, 서버 CORS 허용, 컨트롤러 HTTP Method 변경 GET -> POST
footer :

fix : 카카오 로그인 설정 수정

---

src/main/java/com/team_7/moment_film/domain/user/service/MailService.java

fix: 발신 메일 불러오는 부분 변경

---

src/main/java/com/team_7/moment_film/domain/user/controller/UserController.java
src/main/java/com/team_7/moment_film/domain/user/service/UserService.java

- DB에서 유저정보 삭제
- 사용자가 로그인 시 redis에 저장된 refreshToken 삭제
- 제출한 AccessToken 남은 만료 기간 동안 블랙리스트에 추가

Feat : 회원탈퇴 기능 추가

---

src/main/java/com/team_7/moment_film/domain/customfilter/service/FilterService.java
src/main/java/com/team_7/moment_film/domain/customframe/service/FrameService.java
src/main/java/com/team_7/moment_film/domain/post/service/PostService.java

fix: 반환 status ok -> created 수정

---

src/main/java/com/team_7/moment_film/domain/like/service/LikeService.java
src/main/java/com/team_7/moment_film/domain/post/dto/PostRequestDto.java
src/main/java/com/team_7/moment_film/domain/post/dto/PostResponseDto.java
src/main/java/com/team_7/moment_film/domain/post/entity/Post.java
src/main/java/com/team_7/moment_film/domain/post/service/PostService.java

fix: 게시물,게시물 상세페이지,필터 프레임 id,name 추가!

---

src/main/java/com/team_7/moment_film/domain/like/service/LikeService.java

fix: 좋아요 수정

---

src/main/java/com/team_7/moment_film/domain/customfilter/dto/FilterRequestDto.java
src/main/java/com/team_7/moment_film/domain/customfilter/dto/FilterResponseDto.java
src/main/java/com/team_7/moment_film/domain/customfilter/entity/Filter.java
src/main/java/com/team_7/moment_film/domain/customfilter/service/FilterService.java
src/main/java/com/team_7/moment_film/domain/customframe/service/FrameService.java
src/main/java/com/team_7/moment_film/domain/post/service/PostService.java
src/main/java/com/team_7/moment_film/domain/post/service/S3Service.java

fix: filter 필드 일부 변경

---

src/main/java/com/team_7/moment_film/domain/post/dto/PostResponseDto.java
src/main/java/com/team_7/moment_film/domain/post/service/PostService.java
src/main/java/com/team_7/moment_film/global/util/ClientUtil.java
src/main/java/com/team_7/moment_film/global/util/ViewCountUtil.java

body: Ip를 기준으로 조회수 증가 중복 방지 24시간 기준!

fix: 클라이언트 ip를 가져와서 조회수 증가 중복 방지

---

src/main/java/com/team_7/moment_film/domain/customfilter/service/FilterService.java
src/main/java/com/team_7/moment_film/domain/customframe/service/FrameService.java
src/main/java/com/team_7/moment_film/domain/post/service/PostService.java

body: isBlank만 사용시 null일 경우 NullPointerException 발생
-> null값 함께 체크하는 것으로 수정

fix: 필터,프레임 등록 부분 수정

---

src/main/java/com/team_7/moment_film/domain/customfilter/entity/Filter.java
src/main/java/com/team_7/moment_film/domain/customframe/entity/Frame.java
src/main/java/com/team_7/moment_film/domain/post/entity/Post.java
src/main/java/com/team_7/moment_film/domain/post/service/PostService.java

body: 1:1 -> (filter/frame)1:N(post)

fix: post <->filter,frame 연관관계 수정

---

build.gradle
src/main/java/com/team_7/moment_film/domain/user/controller/UserController.java
src/main/java/com/team_7/moment_film/domain/user/service/UserService.java
src/main/java/com/team_7/moment_film/global/config/KmsConfig.java
src/main/java/com/team_7/moment_film/global/util/EncryptUtil.java
src/main/resources/application.properties

- 암호화 시 EncryptUtil의 encrypt() 메서드 사용,
- 복호화 시 EncryptUtil의 decrypt() 메서드 사용

fix : 민감 정보 양방향 암호화 처리

---

build.gradle
src/main/java/com/team_7/moment_film/domain/post/service/PostService.java
src/main/java/com/team_7/moment_film/domain/post/service/S3Service.java
src/main/java/com/team_7/moment_film/global/lambda/Handler2.java

body: 람다를 이용해서 이미지 리사이징 Marvin 삭제

fear:Lambda:image resized

---

build.gradle

fix:gradle 수정

---

src/main/java/com/team_7/moment_film/global/lambda/Handler2.java

fix: Handler2 error 수정

---

src/main/java/com/team_7/moment_film/domain/user/controller/UserController.java
src/main/java/com/team_7/moment_film/domain/user/entity/User.java
src/main/java/com/team_7/moment_film/domain/user/point/PointCategory.java
src/main/java/com/team_7/moment_film/domain/user/service/GoogleService.java
src/main/java/com/team_7/moment_film/domain/user/service/KakaoService.java
src/main/java/com/team_7/moment_film/domain/user/service/UserService.java
src/main/java/com/team_7/moment_film/global/exception/CustomAuthenticationEntryPoint.java

- 클라이언트가 해당 API에 category를 body에 담아 요청 시 서버에서 정의된 category의 포인트를 적립 또는 차감
- 회원가입 시 1000포인트 기본 값으로 설정(소셜 계정 포함)

feature : 포인트 적립/차감 API 추가

---

src/main/java/com/team_7/moment_film/domain/post/dto/PostResponseDto.java
src/main/java/com/team_7/moment_film/domain/post/service/PostService.java

- 비로그인 사용자가 상세 게시글을 조회했을 경우 isLiked 필드와 isFollowed 필드를 false로 초기화 
- Boolean -> boolean으로 변경

fix:상세조회 수정

---

src/main/java/com/team_7/moment_film/domain/user/entity/User.java
src/main/java/com/team_7/moment_film/domain/user/repository/UserRepository.java
src/main/java/com/team_7/moment_film/domain/user/service/UserService.java

- AES256 알고리즘 적용 후 휴대폰 번호 중복 저장 이슈 확인
- 휴대폰 번호를 AES256 알고리즘으로 암호화 한 값을 DB에 저장함과 동시에 중복 검증을 위해 별도로 휴대폰 번호를 SHA-256 알고리즘으로 해싱 하여 DB에 저장
- 이후 중복된 휴대폰 번호로 가입 시 DB에 저장되어 있는 휴대폰 번호 해싱 값과 클라이언트가 보낸 휴대폰 번호를 해싱 후 값이 일치할 경우 중복으로 판단하여 예외 처리

fix : 회원가입 시 휴대폰 번호 중복 가입 되는 이슈 수정

---

src/main/java/com/team_7/moment_film/domain/post/repository/PostQueryRepository.java
src/main/java/com/team_7/moment_film/domain/post/service/PostService.java

body:전체조회를 할 시 중복 데이터 나오지 않게 수정.

fix:전체조회(최신순,좋아요,조회수) 수정

---

src/main/java/com/team_7/moment_film/domain/follow/repository/FollowRepository.java
src/main/java/com/team_7/moment_film/domain/post/service/S3Service.java
src/main/java/com/team_7/moment_film/domain/user/dto/SearchResponseDto.java
src/main/java/com/team_7/moment_film/domain/user/service/UserService.java

개인정보 수정시 username, phone 중복검사 추가
-> phone 해싱값과 비교, 수정된 user에 phoneHash 추가
s3service 주석추가, 필요없는 코드 수정
mail 인증코드 확인 시에도 provider 추가해서 확인

Fix: 개인정보 수정 중복검사 추가, mail 인증코드 확인 시 provider 추가

---

src/main/java/com/team_7/moment_film/domain/follow/service/FollowService.java
src/main/java/com/team_7/moment_film/domain/post/dto/PostSearchDto.java
src/main/java/com/team_7/moment_film/domain/post/service/S3Service.java
src/main/java/com/team_7/moment_film/domain/user/dto/PopularUserResponseDto.java
src/main/java/com/team_7/moment_film/domain/user/repository/UserRepositoryImpl.java

팔로워순 사용자 조회 - 프로필 이미지, 게시글수 추가
필요없는 부분 정리/개선

fix: 팔로워순 사용자 조회 결과값 추가

---

src/main/java/com/team_7/moment_film/domain/user/repository/UserRepositoryImpl.java
src/main/java/com/team_7/moment_film/global/dto/PageableDto.java

유저 검색시 총 데이터 수 계산하는 부분 추가했습니다.

fix: 유저 검색시 총 데이터 수 추가

---

src/main/java/com/team_7/moment_film/domain/user/repository/UserRepositoryImpl.java

fix: 팔로워 순 유저 조회 쿼리 수정

---

build.gradle
src/test/java/com/team_7/moment_film/MomentFilmApplicationTests.java
src/test/java/com/team_7/moment_film/domain/comment/service/CommentServiceTest.java
src/test/java/com/team_7/moment_film/domain/like/service/LikeServiceTest.java
src/test/java/com/team_7/moment_film/domain/post/service/PostServiceTest.java

body:Comment,Like,PostService 단위 test작성

Jacoco를 이용 하여 TestCode작성

---

src/main/java/com/team_7/moment_film/domain/comment/dto/CommentResponseDTO.java
src/main/java/com/team_7/moment_film/domain/post/dto/PostResponseDto.java
src/main/java/com/team_7/moment_film/domain/post/dto/PostSliceResponse.java
src/main/java/com/team_7/moment_film/domain/post/service/PostService.java
src/main/java/com/team_7/moment_film/domain/subcomment/dto/SubCommentResponseDTO.java

프로필 이미지 추가
